---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup_release:
    name: Setup Release
    outputs:
      changelog_changes: ${{ steps.setup_release.outputs.changelog_changes }}
      changelog_date: ${{ steps.setup_release.outputs.changelog_date }}
      changelog_exists: ${{ steps.setup_release.outputs.changelog_exists }}
      changelog_release_exists: ${{ steps.setup_release.outputs.changelog_release_exists }}
      changelog_url: ${{ steps.setup_release.outputs.changelog_url }}
      changelog_version: ${{ steps.setup_release.outputs.changelog_version }}
      publish_pre_release: ${{ steps.setup_release.outputs.publish_pre_release }}
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      publish_stable_release: ${{ steps.setup_release.outputs.publish_stable_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_build: ${{ steps.setup_release.outputs.release_build }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2023.1210.1904
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs:
      - setup_release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: PlexyGlass.bundle
          submodules: recursive

      - name: Set up Python
        uses: LizardByte/setup-python-action@v2023.1219.224247
        with:
          python-version: '2.7'

      - name: Patch third-party deps
        shell: bash
        working-directory: PlexyGlass.bundle/third-party
        run: |
          patch_dir=${{ github.workspace }}/PlexyGlass.bundle/patches

          # youtube-dl patches
          pushd youtube-dl
          git apply -v "${patch_dir}/youtube_dl-compat.patch"
          popd

      - name: Set up Python Dependencies
        shell: bash
        working-directory: PlexyGlass.bundle
        run: |
          echo "Installing Requirements"
          python --version
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade pip setuptools

          # install dev requirements
          python -m pip install --upgrade -r requirements-dev.txt

          python -m pip install --upgrade --target=./Contents/Libraries/Shared -r \
            requirements.txt --no-warn-script-location

      - name: Build plist
        working-directory: PlexyGlass.bundle
        env:
          BUILD_VERSION: ${{ needs.setup_release.outputs.release_tag }}
        run: |
          python ./scripts/build_plist.py

      - name: Package Release
        shell: bash
        run: |
          7z \
            "-xr!*.git*" \
            "-xr!*.pyc" \
            "-xr!__pycache__" \
            "-xr!plexhints*" \
            "-xr!PlexyGlass.bundle/.*" \
            "-xr!PlexyGlass.bundle/cache.sqlite" \
            "-xr!PlexyGlass.bundle/DOCKER_README.md" \
            "-xr!PlexyGlass.bundle/Dockerfile" \
            "-xr!PlexyGlass.bundle/docs" \
            "-xr!PlexyGlass.bundle/scripts" \
            a "./PlexyGlass.bundle.zip" "PlexyGlass.bundle"

          mkdir artifacts
          mv ./PlexyGlass.bundle.zip ./artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PlexyGlass.bundle
          if-no-files-found: error  # 'warn' or 'ignore' are also available, defaults to `warn`
          path: |
            ${{ github.workspace }}/artifacts

      - name: Create/Update GitHub Release
        if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
        uses: LizardByte/create-release-action@v2023.1210.832
        with:
          allowUpdates: true
          body: ''
          discussionCategory: announcements
          generateReleaseNotes: true
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: ${{ needs.setup_release.outputs.publish_pre_release }}
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}

  pytest:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: PlexyGlass.bundle

      - name: Extract artifacts zip
        shell: bash
        run: |
          # extract zip
          7z x PlexyGlass.bundle.zip -o.

          # move all files from "PlexyGlass.bundle" to root, with no target directory
          cp -r ./PlexyGlass.bundle/. .

          # remove zip
          rm PlexyGlass.bundle.zip

      - name: Set up Python
        uses: LizardByte/setup-python-action@v2023.1219.224247
        with:
          python-version: '2.7'

      - name: Install python dependencies
        shell: bash
        run: |
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade \
            pip setuptools wheel
          python -m pip --no-python-version-warning --disable-pip-version-check install -r requirements-dev.txt

      - name: Test with pytest
        id: test
        shell: bash
        run: |
          python -m pytest \
            -rxXs \
            --tb=native \
            --verbose \
            --cov=Contents/Code \
            --cov=Contents/Services \
            tests

      - name: Upload coverage
        # any except canceled or skipped
        if: always() && (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ runner.os }}
